import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/wagmi/wagmi-provider";

import Header from "@/shared/ui/header";
import Sidebar from "@/shared/ui/sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="scheme-light dark:scheme-dark">
			<body>
				<Providers>
					<div className="flex min-h-screen flex-col">
						{/* Header */}
						<Header />

						{/* Main layout */}
						<div className="flex flex-1">
							{/* Sidebar */}
							<Sidebar />

							{/* Page content */}
							<main className="flex-1">{children}</main>
						</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
