import type { Metadata } from "next";
import "./globals.css";
import { WagmiProviders } from "@/providers/wagmi/wagmi-provider";
import { UserTokensProvider } from "@/providers/user-tokens-provider";
import Header from "@/widjets/header";
import Sidebar from "@/widjets/sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="scheme-light dark:scheme-dark">
			<body>
				<WagmiProviders>
					<UserTokensProvider>
						<div className="flex min-h-screen flex-col">
							{/* Header */}
							<Header />

							{/* Main layout */}
							<div className="flex flex-1">
								{/* Sidebar */}
								<Sidebar />

								{/* Page content */}
								<main className="flex-1">{children}</main>
							</div>
						</div>
					</UserTokensProvider>
				</WagmiProviders>
			</body>
		</html>
	);
}
